services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: revmaster
    restart: unless-stopped
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - ./data:/app/data
